# Your Website Title
title: Majid Iranpour Website

# Your Website URL
url: 'http://majidmc2.github.io'

# Leave it default
baseurl: '' 

# Google Analytics
ga_index: UA-XXXXXXXX-X
ga_cv: UA-XXXXXXXX-X

# Index page and Profile Information
name: Majid Iranpour
tagline: Security Engineer, Software Security Developer
pic: profile.png # profile.png can be found at /assets/images/profile.png
description: Security Researcher \ Bug Hunter \ Software Security Developer
description_tiny: ''
website: majidmc2.github.io # do not add http://
linkedin: majidmc2
github: majidmc2
twitter: '@_majidmc2'

# Files or folders to be excluded
exclude: [gitbook_source_code/]

# All the plugins for Jekyll
plugins:
  - jekyll-sitemap
  - wdm